#!/usr/bin/env bash

## This script bootstraps the nixos configurations by copying the relevant files to 
#    /etc/nixos/
# This script must be run as root.

OWNER=$(whoami)
if [ "$OWNER" = "root" ]; then
  mkdir -p /etc/nixos/nixos-configs
  cp ./*.nix /etc/nixos/nixos-configs/
  cp -sf /etc/nixos/nixos-configs/configuration.nix /etc/nixos/configuration.nix
else
  echo "You are not root. Please run this script as root."
fi

